import type { Job } from './types';
import { PlaceHolderImages } from './placeholder-images';

const logos = PlaceHolderImages.filter(img => img.id.startsWith('company-logo-'));

export const jobs: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Frontend Engineer',
    company: 'Safaricom PLC',
    location: 'Nairobi, Kenya',
    description: 'We are looking for a skilled Senior Frontend Engineer to join our team. You will be responsible for building the client-side of our web applications. You should be able to translate our company and customer needs into functional and appealing interactive applications.',
    postedDate: new Date('2024-07-20T09:00:00Z').toISOString(),
    category: 'Frontend',
    applyUrl: '#',
    companyLogo: logos[0],
  },
  {
    id: 'job-2',
    title: 'Backend Developer (Node.js)',
    company: 'Africa\'s Talking',
    location: 'Nairobi, Kenya',
    description: 'Join our backend team to build and maintain scalable services and APIs. You will work with a team of developers to design, implement, and ship new features. Strong knowledge of Node.js, databases, and cloud services is required.',
    postedDate: new Date('2024-07-19T14:30:00Z').toISOString(),
    category: 'Backend',
    applyUrl: '#',
    companyLogo: logos[1],
  },
  {
    id: 'job-3',
    title: 'Full Stack Developer',
    company: 'Cellulant',
    location: 'Remote (Kenya)',
    description: 'We are hiring a Full Stack Developer to work on both our frontend and backend systems. This role requires proficiency in React and Python/Django. Experience with payment systems is a plus.',
    postedDate: new Date('2024-07-21T11:00:00Z').toISOString(),
    category: 'Full Stack',
    applyUrl: '#',
    companyLogo: logos[2],
  },
  {
    id: 'job-4',
    title: 'Android Mobile Developer',
    company: 'M-KOPA Solar',
    location: 'Nairobi, Kenya',
    description: 'Develop and maintain our native Android application. You will be part of a team that is passionate about creating a great user experience for our customers across Africa. Strong Kotlin skills are a must.',
    postedDate: new Date('2024-07-18T08:00:00Z').toISOString(),
    category: 'Mobile',
    applyUrl: '#',
    companyLogo: logos[3],
  },
  {
    id: 'job-5',
    title: 'DevOps Engineer',
    company: 'Twiga Foods',
    location: 'Nairobi, Kenya',
    description: 'We\'re seeking a DevOps Engineer to manage our cloud infrastructure on AWS. You will be responsible for CI/CD pipelines, monitoring, and ensuring the reliability and scalability of our platform.',
    postedDate: new Date('2024-07-20T16:00:00Z').toISOString(),
    category: 'DevOps',
    applyUrl: '#',
    companyLogo: logos[4],
  },
    {
    id: 'job-6',
    title: 'React Native Developer',
    company: 'Lori Systems',
    location: 'Nairobi, Kenya',
    description: 'Build cross-platform mobile applications for our logistics platform using React Native. Collaborate with product managers and designers to deliver high-quality mobile experiences.',
    postedDate: new Date('2024-07-17T13:20:00Z').toISOString(),
    category: 'Mobile',
    applyUrl: '#',
    companyLogo: logos[0],
  },
  {
    id: 'job-7',
    title: 'Data Scientist',
    company: 'Equity Bank',
    location: 'Nairobi, Kenya',
    description: 'Analyze large datasets to extract meaningful insights and build predictive models. You will work on projects related to credit scoring, fraud detection, and customer segmentation. Proficiency in Python, R, and SQL required.',
    postedDate: new Date('2024-07-21T09:30:00Z').toISOString(),
    category: 'Data Science',
    applyUrl: '#',
    companyLogo: logos[2],
  },
  {
    id: 'job-8',
    title: 'Junior Backend Engineer (Go)',
    company: 'Sendy',
    location: 'Remote',
    description: 'Exciting opportunity for a junior backend developer to learn and grow. You will be working with Go to build microservices for our logistics and delivery platform. Mentorship provided.',
    postedDate: new Date().toISOString(),
    category: 'Backend',
    applyUrl: '#',
    companyLogo: logos[1],
  },
  {
    id: 'job-9',
    title: 'Urgent Junior Developer - High Pay!',
    company: 'Easy Money Inc.',
    location: 'Remote',
    description: 'We need a junior developer. No experience needed! We pay $2000 per week. You just need to pay a small fee of $50 for training materials. Very easy job, work from home. Apply now!',
    postedDate: new Date('2024-07-15T10:00:00Z').toISOString(),
    category: 'Full Stack',
    applyUrl: '#',
    companyLogo: logos[5],
  },
  {
    id: 'job-10',
    title: 'Lead Frontend Developer (Vue.js)',
    company: 'iHub',
    location: 'Nairobi, Kenya',
    description: 'Lead our frontend team in building innovative products. We are a Vue.js shop. You should have experience leading a team and a strong portfolio of complex web applications.',
    postedDate: new Date('2024-07-16T18:00:00Z').toISOString(),
    category: 'Frontend',
    applyUrl: '#',
    companyLogo: logos[4],
  }
];
